import pandas as pd
import matplotlib.pyplot as plt
import glob
import os

def generate_plots():
    results = []
    
    # Define your specific files
    files_map = {
        "Baseline 1s": "results_baseline_1s.csv",
        "Baseline 5s": "results_baseline_5s.csv",
        "Baseline 30s": "results_baseline_30s.csv",
        "Loss 2%": "results_loss_2pct_1s.csv",
        "Loss 5%": "results_loss_5pct_1s.csv"
    }

    for label, filename in files_map.items():
        if os.path.exists(filename):
            try:
                df = pd.read_csv(filename)
                # Normalize columns
                df.columns = [c.strip() for c in df.columns]
                
                total = len(df)
                if total > 0:
                    dup_rate = (df['duplicate_flag'].sum() / total) * 100
                    gap_rate = (df['gap_flag'].sum() / total) * 100
                    # Fixed size: Header (12) + Payload (20)
                    bytes_val = 32
                    
                    # Extract loss pct for sorting
                    loss_pct = 0
                    if "2%" in label: loss_pct = 2
                    elif "5%" in label: loss_pct = 5
                    
                    results.append({
                        "Label": label,
                        "Loss_Pct": loss_pct,
                        "Bytes": bytes_val,
                        "Dup_Rate": dup_rate,
                        "Gap_Rate": gap_rate
                    })
            except Exception as e:
                print(f"Error reading {filename}: {e}")

    df_res = pd.DataFrame(results)

    # Plot 1: Bytes vs Interval (Baselines)
    df_base = df_res[df_res['Label'].str.contains("Baseline")]
    if not df_base.empty:
        plt.figure(figsize=(8, 6))
        # Extract interval text (e.g., "1s")
        intervals = df_base['Label'].apply(lambda x: x.split()[1])
        plt.bar(intervals, df_base['Bytes'], color='skyblue')
        plt.title("Bytes per Report vs Reporting Interval")
        plt.ylabel("Bytes (Header + Payload)")
        plt.savefig("bytes_per_report.png")
        print("Generated bytes_per_report.png")

    # Plot 2: Reliability (Baseline 1s + Loss)
    df_loss = df_res[ (df_res['Label'] == "Baseline 1s") | (df_res['Label'].str.contains("Loss")) ].sort_values("Loss_Pct")
    if not df_loss.empty:
        plt.figure(figsize=(10, 6))
        plt.plot(df_loss['Loss_Pct'], df_loss['Gap_Rate'], 'r-o', label='Sequence Gap Rate')
        plt.plot(df_loss['Loss_Pct'], df_loss['Dup_Rate'], 'g-s', label='Duplicate Rate')
        plt.title("Protocol Reliability vs Network Loss")
        plt.xlabel("Packet Loss (%)")
        plt.ylabel("Rate (%)")
        plt.xticks([0, 2, 5])
        plt.legend()
        plt.grid(True)
        plt.savefig("duplicate_vs_loss.png")
        print("Generated duplicate_vs_loss.png")

if __name__ == "__main__":
    generate_plots()