import csv
import os
import sys

# File generated by your jitter test
FILE_PATH = "results_jitter_test_1s.csv"

def check_jitter():
    if not os.path.exists(FILE_PATH):
        print(f"[ERR] File {FILE_PATH} not found. Run the test first!")
        return

    latencies = []

    try:
        with open(FILE_PATH, 'r') as f:
            reader = csv.DictReader(f)
            # Normalize headers (strip spaces)
            reader.fieldnames = [name.strip() for name in reader.fieldnames]

            for row in reader:
                try:
                    # Parse timestamps
                    send_ts = float(row['timestamp'])
                    recv_ts = float(row['arrival_time'])
                    
                    # Calculate Latency
                    latency = recv_ts - send_ts
                    latencies.append(latency)
                except ValueError:
                    continue

        if not latencies:
            print("[ERR] No valid data found in CSV.")
            return

        # --- Statistics ---
        count = len(latencies)
        avg_lat = sum(latencies) / count
        min_lat = min(latencies)
        max_lat = max(latencies)
        jitter_range = max_lat - min_lat

        # Calculate Standard Deviation (Optional, but good for verification)
        variance = sum([((x - avg_lat) ** 2) for x in latencies]) / count
        std_dev = variance ** 0.5

        # --- Report ---
        print("-" * 40)
        print(f"JITTER TEST VERIFICATION (No Pandas)")
        print("-" * 40)
        print(f"Packet Count  : {count}")
        print(f"Avg Latency   : {avg_lat*1000:.2f} ms  (Target: ~100.00 ms)")
        print(f"Min Latency   : {min_lat*1000:.2f} ms  (Target: ~90.00 ms)")
        print(f"Max Latency   : {max_lat*1000:.2f} ms  (Target: ~110.00 ms)")
        print(f"Jitter Range  : {jitter_range*1000:.2f} ms (Target: ~20.00 ms)")
        print(f"Std Dev       : {std_dev*1000:.2f} ms")
        print("-" * 40)

        # --- Verdict ---
        # We expect mean around 0.1s and visible jitter (range > 10ms)
        if 0.09 <= avg_lat <= 0.11 and jitter_range > 0.01:
            print("✅ SUCCESS: Latency and Jitter detected correctly.")
        else:
            print("❌ FAILURE: Results do not match the expected profile.")
            print("   (Ensure 'sudo tc qdisc' commands ran successfully)")

    except Exception as e:
        print(f"[ERR] Failed to process file: {e}")

if __name__ == "__main__":
    check_jitter()